version: '3.8'

services:
  mysql:
    image: mysql:5.7.44
    container_name: mysql_virtualknowledge
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - springnet
      
	volumes:
	  - ../db_data:/var/lib/mysql
	  - ../initdb:/docker-entrypoint-initdb.d
volumes:
	db_data:

networks:
  springnet:
    driver: bridge
