version: '3.8'

services:
  mysql:
    image: mysql:5.7.44
    container_name: mysql_virtualknowledge
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - springnet
    volumes:
      
      - ./initdb:/docker-entrypoint-initdb.d
  
#  app:
#  
#    build: 
#      context: . 
#      dockerfile: Dockerfile
#    container_name: spring_boot_app
#    restart: always
#    ports:
#      - "8080:8080"
#    networks:
#      - springnet
#  
#    depends_on:
#      mysql:
#        condition: service_started 
#    environment:
#    
#    
##      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db
 #     SPRING_DATASOURCE_USERNAME: admin
 #     SPRING_DATASOURCE_PASSWORD: admin
    

volumes:
  db_data:

networks:
  springnet:
    driver: bridge
