spring.application.name=virtualknowledge

spring.datasource.url=jdbc:mysql://localhost:3306/db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
server.port=8080

api.key=claveparaapikey
api.secret=secretparaapisecret
api.service.name=Servicio-SSO-Fijo

jwt.secret=MyUltraSecretKeyForJwtSecurity2025!!!
jwt.expiration=3600000